name: "Backend: tests & sonar"

on:
  workflow_call:
    inputs:
      event_name:
        description: 'Original github.event_name'
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # https://github.com/actions/checkout/releases/tag/v6.0.3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # https://github.com/actions/setup-java/releases/tag/v4
        with:
          java-version-file: '.java-version'
          distribution: 'zulu'
          cache: 'gradle'

      - name: "Tests"
        run: |
          ./gradlew :api:test

      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # https://github.com/codecov/codecov-action/releases/tag/v6.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: api/build/reports/jacoco/test/jacocoTestReport.xml
          flags: backend
          fail_ci_if_error: false
